- arguments:
  - -XAllowAmbiguousTypes
  - -XConstraintKinds
  - -XDataKinds
  - -XDerivingStrategies
  - -XFlexibleInstances
  - -XFunctionalDependencies
  - -XOverloadedStrings
  - -XPolyKinds
  - -XScopedTypeVariables
  - -XTypeApplications
  - -XTypeFamilies
  - -XTypeOperators

- ignore: {name: "Reduce duplication"}
