sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  # Cabal
  - ghc: 8.6.5
    cabal: "2.4"

  - ghc: 8.8.2
    cabal: "3.0"

  # Stack
  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack-8.6.5.yaml"
    cabal: "2.4"

  # Stack
  - ghc: 8.8.2
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
    cabal: "3.0"

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-update
      cabal v2-build --enable-tests --enable-benchmarks
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal v2-test --enable-tests
    else
      set -euo pipefail
      stack test --system-ghc
      stack examples/custom.hs
      stack examples/example.hs
      stack examples/generate.hs
      stack examples/parse.hs
      stack examples/render.hs
    fi

notifications:
  email: false
